In [30]:
import torch
import torch.nn as nn
import numpy as np
import time

device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [31]:
randint = torch.randint(-100, 100, (6,))
randint

tensor([-36, -35,  -7,  17,  12,  51])

In [32]:
# probability tensor
probabilities = torch.tensor([0.1, 0.9]) # 10% chance of getting 0, 90% chance of getting 1 (0 and 1 are the indices of the tensor)
# draw a number of samples from a multinomial distribution
samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

probabilities2 = torch.tensor([0.2, 0.5, 0.3])
# draw a number of samples from a multinomial distribution
samples2 = torch.multinomial(probabilities2, num_samples=10, replacement=True)
print(samples2)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
tensor([2, 2, 2, 0, 1, 0, 1, 2, 2, 0])


In [33]:
tensor = torch.tensor([1, 2, 3])
output = torch.cat((tensor, torch.tensor([5])), dim=0) # concatenates tensor1 and tensor2 in the first parametre (t1, t2)
output

tensor([1, 2, 3, 5])

In [34]:
output = torch.tril(torch.ones(5, 5))
output

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [35]:
output = torch.triu(torch.ones(5, 5))
output

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [36]:
output = torch.zeros(5, 5).masked_fill(torch.tril(torch.ones(5, 5)) == 0, float('-inf'))
output

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [37]:
torch.exp(output)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [38]:
input = torch.zeros(2, 3, 4)
output = input.transpose(0, 2)
output.shape

# input2 = torch.zeros(4, 3)
# output2 = input2.transpose(0, 1)
# output2.shape
# prints out:
# torch.Size([3, 4])

torch.Size([4, 3, 2])

In [39]:
t1 = torch.tensor([1, 2, 3])
t2 = torch.tensor([4, 5, 6])
t3 = torch.tensor([7, 8, 9])

stacked = torch.stack([t1, t2, t3])
stacked

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [40]:
sample = torch.tensor([10., 10., 10.])
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([ 7.2595,  0.0932, -5.4034], grad_fn=<SqueezeBackward4>)


In [41]:
import torch.nn.functional as F

# create tensor
t1 = torch.tensor([1.0, 2.0, 3.0])

# apply softmax using torch.nnn.functional.softmax()
softmax_output = F.softmax(t1, dim=0)
print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [42]:
# We initialize the embedding layer by giving it dimensions
vocab_size = 10000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Then we create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding layer onto the input indices
embedded_output = embedding(input_indices)

# output will be a tensor of shape (4, 100) where 4 is the number of indices
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)

torch.Size([4, 100])


In [43]:
a = torch.tensor([[1, 2], [3, 4], [5, 6]])
b = torch.tensor([[7, 8, 9], [10, 11, 12]])
# @ is for the dot-product operation
print(a @ b)
# alternate way to do this is to use matmul
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [44]:
int_64 = torch.randint(1, (3, 2)).float()
# type int64
float_32 = torch.rand(2, 3)
# type float32
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [46]:
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x,y,z)
print(a.shape)
# print(x, y, z)

torch.Size([2, 3, 5])
torch.Size([2, 3, 5])


In [10]:
tensor = torch.tensor([[0.1, 1.2], [3.1, 4.2], [5.7, 6.8]])
tensor

tensor([[0.1000, 1.2000],
        [3.1000, 4.2000],
        [5.7000, 6.8000]])

In [9]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
empty = torch.empty(2, 3)
empty

tensor([[5.4530e+08, 1.6788e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [14]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [16]:
linspace = torch.linspace(3, 10, steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [17]:
logspace = torch.logspace(-10, 10, steps=5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [19]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
a = torch.empty((2, 3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])